name: Print Pagoda Token

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PAGODA_TOKEN: ${{ secrets.PAGODA_TOKEN }}
    steps:
      - name: Print Pagoda Token
        run: echo "${PAGODA_TOKEN:0:5}"
